name: falcon
description: A sample command-line application.
version: 1.0.0
homepage: https://github.com/blendthink/falcon
repository: https://github.com/blendthink/falcon
documentation: https://github.com/blendthink/falcon
issue_tracker: https://github.com/blendthink/falcon/issues

executables:
  falcon:

environment:
  sdk: '>=2.17.3 <3.0.0'

dependencies:
  args: ^2.3.1
  googleapis: ^9.1.0
  googleapis_auth: ^1.3.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
