name: falcon
description: A command-line application for quickly uploading Flutter apps to the store.
version: 1.0.0
homepage: https://github.com/blendthink/falcon
repository: https://github.com/blendthink/falcon
documentation: https://github.com/blendthink/falcon
issue_tracker: https://github.com/blendthink/falcon/issues

executables:
  falcon:

environment:
  sdk: '>=2.17.3 <3.0.0'

dependencies:
  args: ^2.3.1
  googleapis: ">=9.1.0 <11.0.0"
  googleapis_auth: ^1.3.1
  pubspec_parse: ^1.2.0

dev_dependencies:
  build_runner: ^2.1.11
  lints: ^2.0.0
  pubspec_builder: ^1.0.0
  test: ^1.16.0
