name: falcon
description: A sample command-line application.
version: 1.0.0
homepage: https://github.com/blendthink/falcon
repository: https://github.com/blendthink/falcon
documentation: https://github.com/blendthink/falcon
issue_tracker: https://github.com/blendthink/falcon/issues

executables:
  falcon:

environment:
  sdk: '>=2.17.3 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
